version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: registry_password
      MYSQL_DATABASE: schema_registry
      MYSQL_USER: registry_user
      MYSQL_PASSWORD: registry_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  repo:
    image: vaimr/avro-repo
    restart: always
    ports:
      - 9090:9090
